services:
  krakend:
    image: devopsfaith/krakend:2.9
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    networks:
      - observability
  prometheus:
    image: prom/prometheus:v2.53.4
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - "./config/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml"
    networks:
      - observability

networks:
  observability:
    driver: bridge

volumes:
  grafana-data:
